name: hadui
version: 0.1.0.0
github: complyue/hadui
license: BSD3
author: Compl Yue
maintainer: compl.yue@icloud.com
copyright: 2019 Compl Yue

extra-source-files:
  - README.md
  - ChangeLog.md

data-files:
  - web/**/*

synopsis: Web front UI for interactive stack projects
category: Development Web

description: Please see the README on Github at <https://github.com/complyue/hadui>

dependencies:
  - ghc >= 8.6
  - unix
  - process
  - network
  - websockets

  - base
  - rio
  - text
  - bytestring
  - directory
  - HsYAML
  - aeson
  - aeson-qq
  - unliftio
  - snap-core
  - snap-server

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hadui:
    main: Main.hs
    source-dirs: pub-main
    dependencies:
      - hadui

    ghc-options:
      # in publication mode, the `hadui` executable is just a
      # thin wrapper to launch `stack ghci` with 'HaduiPub' as
      # the interactive GHC frontend.
      # but more than 1 native threads could help avoiding quirks
      # in single-threaded cooperative scheduling.
      - -threaded
      - -rtsopts
      - -with-rtsopts=-maxN2

  hadui-dev:
    main: Main.hs
    source-dirs: dev-main
    dependencies:
      - hadui

    ghc-options:
      # in development mode, the hadui process only handles light
      # http traffics, no need of much parallelism.
      # but more than 1 native threads could help avoiding quirks
      # in single-threaded cooperative scheduling.
      - -threaded
      - -rtsopts
      - -with-rtsopts=-maxN2
# TODO define hadui-dap to be integrated with VSCode to provide
#      debuggability.
